<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.2"/>
        <PackageReference Include="FluentMigrator.Runner.Core" Version="8.0.0"/>
        <PackageReference Include="FluentMigrator.Runner.SQLite" Version="8.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0"/>
        <PackageReference Include="xunit" Version="2.9.2"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Blockpit.Mediator\Blockpit.Mediator.csproj"/>
        <ProjectReference Include="..\Blockpit.Migrations\Blockpit.Migrations.csproj"/>
    </ItemGroup>

</Project>
